### ISSUE TITLE
ASFW License

### ISSUE THREAD

**Issue by SpiceyWolf** [aeirex/MirageWorlds#1]
This is the official repo of asfw, linked specifically to the license. Eclipse DOES NOT and has NEVER owned my source code. I have never given permission for license to be changed either.

ASFW stands for Archaicsoft Framework.

https://gitlab.com/ArchaicSoft/miscellaneous/Asfw-CS/-/blob/master/LICENSE

**Comment by aeirex** [comment]
I updated the license. Let me know if you have any other concerns.

**Comment by SpiceyWolf** [comment]
oof xD you changed the wrong one... the base repo was license of the mirage worlds project lol

**Comment by aeirex** [comment]
I erased the LICENSE file in Network.

**Comment by XerShade** [comment]
I put it back, there's an open pull request for it.
